# Введення в PyTorch і персептрон

*pip install torch*

Перцептрон (персептрон) - модель, що діє схожим з біологією принципом "збудження" і його передачі далі.
Складаються з вхідного шару - сенсорів, проміжних (прихованих) шарів та вихідного шару - вирішувача.

Навчання перцептрона - процес підбору, коригування вагових коефіцієнтів зв'язків, що поєднують проміжні та вихідні шари. Розрізняють "прямий" хід навчання, коли збільшуються (або зменшуються) коефіцієнти для усіх активованих елементів при "демонстрації" прикладів різних класів. Та "зворотній" хід, коли результат зміни втрат впливає на коригування коефіцієнтів. (Втрати - оцінка помилок передбачення). Для реалізації зворотного ходу необхідно забезпечувати збереження відомостей про попередні стани коефіцієнтів для чого потрібні спеціалізовані типи даних - тензори.

In [2]:
import torch

## Бізнес-контекст
Компанія HealthRisk Analytics будує прототип моделі, яка за простими показниками (наприклад, вік та індекс маси тіла) прогнозує рівень страхового ризику клієнта.

Ваше завдання — змоделювати основу цієї системи, використовуючи PyTorch: спочатку — один лінійний нейрон, потім — малу нейромережу.

*Навчання перцептронів та нейромереж здійснюється у певному бізнес-контексті. Одним з недоліків нейромереж є їх сильна залежність від "масштабу" - представлення даних, що обробляються.*

## Завдання 1
Створіть тензори та виконайте базові операції.
Уявіть, що кожен тензор — це стовпець даних про клієнтів (вік, вага, зріст).
- Створіть 1D, 2D і 3D тензори(torch.manual_seed(42)).
- Виконайте операції додавання і поелементного множення, щоб обчислити умовний показник ризику.
- Увімкніть requires_grad=True для одного тензора, перевірте наявність grad_fn.

In [5]:
# сідування (seed, seeding) - встановлення початкового стану генераторів випадкових чисел для 
# забезпечення відновлюваності експериментів
torch.manual_seed(42)

# Створіть 1D (вік)
age = torch.randint(18, 75, (5,))
age

tensor([33, 50, 67, 70, 39])

In [8]:
# Створіть 2D (вік, вага)
age_weight = torch.randn(5, 2)  # n - normal distribution
age_weight[:,0] = 42 + 21 * age_weight[:,0]
age_weight[:,1] = 75 + 25 * age_weight[:,1]
age_weight

tensor([[ 41.7258, 114.6494],
        [ 20.6092,  64.5493],
        [ 35.8365, 110.8213],
        [ 53.1554,  68.7932],
        [ 38.3556, 109.6239]])

In [12]:
# Створіть 3D (вік, вага, зріст)
age_weight_height = torch.randn(5, 3, requires_grad=True) 
# включення стеження за градієнтом забороняє прямі операції з перетворення вмісту тензора
# за потреби таких змін слід відключити стеження за градієнтом
with torch.no_grad() :
    age_weight_height[:,0] = 42 + 21 * age_weight_height[:,0]
    age_weight_height[:,1] = 75 + 25 * age_weight_height[:,1]
    age_weight_height[:,2] = 155 + 15 * age_weight_height[:,2]
age_weight_height

tensor([[ 42.2902,  35.4609, 170.9577],
        [ 59.2751,  55.4435, 142.0216],
        [ 55.2155,  85.4507, 128.4370],
        [ 71.3362,  70.1113, 145.1881],
        [ 48.8336, 104.9226, 162.9530]], requires_grad=True)

In [13]:
# Виконайте операції додавання і поелементного множення, щоб обчислити умовний показник ризику.
risk = 2 * age_weight_height[:,0] + 3 * (age_weight_height[:,1] - 75) + 0.01 * age_weight_height[:,2]
risk

tensor([-32.3273,  61.3009, 143.0675, 129.4581, 189.0646],
       grad_fn=<AddBackward0>)