# NumPy
*pip install numpy*

Пакет для математичних типів даних (векторів, матриць) та мат. операцій з ними

In [1]:
import numpy as np

## Завдання 1
Створіть одновимірний масив із 10 випадкових чисел від 0 до 100.
- Збережіть масив у змінну і виведіть його на екран.
- Знайдіть мінімальне, максимальне та середнє значення масиву за допомогою вбудованих функцій NumPy.
- Відсортуйте масив за зростанням і виведіть результат.
- Відобразіть масив до і після сортування.

In [2]:
arr1 = np.random.randint(0, 100, size=10)
print(arr1)

[36 45  8 96 18 95 18  2 18  0]


In [4]:
print("min = %d, max = %d, avg = %.1f" % (np.min(arr1), np.max(arr1), np.mean(arr1)))

min = 0, max = 96, avg = 33.6


In [5]:
print(arr1)
print(np.sort(arr1))
print(arr1)  # Висновок - масив не змінюється, створюється копія

[36 45  8 96 18 95 18  2 18  0]
[ 0  2  8 18 18 18 36 45 95 96]
[36 45  8 96 18 95 18  2 18  0]


## Завдання 2
Створіть двовимірний масив розміром 4×4, заповнений випадковими цілими числами від 1 до 50.
- Виведіть масив у читабельному вигляді (у вигляді таблиці).
- Знайдіть суму елементів за кожним рядком і за кожним стовпчиком (використовуйте параметр axis).
- Визначте загальне середнє значення масиву.
- Виведіть усі результати в зручному вигляді
(наприклад: "Суми за рядками: ...","Суми за стовпцями: ...").

In [6]:
# Створіть двовимірний масив розміром 4×4, заповнений випадковими цілими числами від 1 до 50.
arr2 = np.random.randint(1, 50, size=(4,4))

In [7]:
# Виведіть масив у читабельному вигляді (у вигляді таблиці).

In [11]:
print(arr2)

[[10 17 21 18]
 [32 32  1 11]
 [ 3 12  9 31]
 [36  9 24 14]]


In [13]:
print(*(a for a in arr2), sep='\n')

[10 17 21 18]
[32 32  1 11]
[ 3 12  9 31]
[36  9 24 14]


In [15]:
# Знайдіть суму елементів за кожним рядком і за кожним стовпчиком (використовуйте параметр axis).
print(np.sum(arr2, axis=0))  # axis=0 - за стовпчиками
print(np.sum(arr2, axis=1))  # axis=1 - за рядками

[81 70 55 74]
[66 76 55 83]


In [29]:
# zip(arr1,arr2) - поєднує множини за принципом [ [arr1[0], arr2[0]], [arr1[1], arr2[1]], ... ] 
# map(fun, arr) - застосовує функцію fun до кожного елементу arr
# " ".join(arr) - поєднує всі елементи arr через пробіл (вимагає, щоб елементи arr були рядками)
print(
    *( f"{x} | {y}" for x, y in zip( arr2, np.sum(arr2, axis=1) ) ), 
    "------------------",
    # f"{np.sum(arr2, axis=0)} {np.mean(arr2)}",
    " ".join(map(str, (np.sum(arr2, axis=0), '|', np.mean(arr2)))),
    sep='\n'
)

[10 17 21 18] | 66
[32 32  1 11] | 76
[ 3 12  9 31] | 55
[36  9 24 14] | 83
------------------
[81 70 55 74] | 17.5


<hr/>

## Завдання 3
Створіть масив розміром 3×5, заповнений числами від 0 до 14.
- Виведіть вихідний масив.
- Виконайте транспонування масиву (рядки стають стовпцями, а стовпці — рядками).
- Застосуйте операцію reshape, щоб отримати масив 5×3.
- Відобразіть результати на екран.

In [30]:
arr3 = np.random.randint(0, 14, size=(3,5))
print(arr3)

[[13 11  7  8 11]
 [ 8  2  7  6  3]
 [ 5 10  1 11 11]]


In [31]:
# Виконайте транспонування масиву (рядки стають стовпцями, а стовпці — рядками).
np.transpose(arr3)

array([[13,  8,  5],
       [11,  2, 10],
       [ 7,  7,  1],
       [ 8,  6, 11],
       [11,  3, 11]], dtype=int32)

In [32]:
# Застосуйте операцію reshape, щоб отримати масив 5×3.
np.reshape(arr3, shape=(5,3) )  # реорганізація до нової форми, без збереження логіки розподілу

array([[13, 11,  7],
       [ 8, 11,  8],
       [ 2,  7,  6],
       [ 3,  5, 10],
       [ 1, 11, 11]], dtype=int32)

In [34]:
print(arr1)
np.reshape(arr1, shape=(-1,1) )  # особливий варіант - створення "обгортки" для елементів масиву

[36 45  8 96 18 95 18  2 18  0]


array([[36],
       [45],
       [ 8],
       [96],
       [18],
       [95],
       [18],
       [ 2],
       [18],
       [ 0]], dtype=int32)

## Завдання 4
Створіть масив розміром 10×10, заповнений випадковими числами з плаваючою крапкою від 0 до 1.
- Знайдіть мінімальне та максимальне значення в усьому масиві.
- Визначте індекси мінімального та максимального елементів
- (наприклад: (рядок, стовпець)).
- Виведіть сам масив і окремо знайдені значення разом з їхніми індексами.

In [48]:
arr4 = np.random.rand(10,10)
# print(*(f"{x:.3f}" for a in arr4 for x in a)) - всі числа в один рядок
# ' '.join(f"{x:.3f}" for x in arr4[0]) - числа першого рядка масива
print(*(
        ' '.join(f"{x:.2f}" for x in a) 
                for a in arr4
      ), 
      sep='\n')  # всі рядки через \n

0.54 0.96 0.06 0.69 0.91 0.07 0.20 0.55 0.72 0.52
0.02 0.34 0.23 0.75 0.10 0.76 0.71 0.80 0.59 0.28
0.11 0.72 0.70 0.47 0.28 0.35 0.86 0.97 0.79 0.70
0.04 0.21 0.62 0.40 0.42 0.56 0.73 0.34 0.65 0.78
0.83 0.41 0.21 0.03 0.93 0.81 0.01 0.64 0.74 0.69
0.64 0.47 0.30 0.50 0.94 0.14 0.13 0.67 0.25 0.73
0.82 0.73 0.54 0.27 0.17 0.14 0.24 0.99 0.70 0.34
0.64 0.95 0.13 0.57 0.84 0.19 0.70 0.28 0.93 0.45
0.49 0.00 0.85 0.95 0.05 0.31 0.71 0.14 0.42 0.96
0.38 0.20 0.23 0.31 0.50 0.12 0.47 0.21 0.46 0.78


In [51]:
# Визначте індекси мінімального та максимального елементів
min_index = np.argmin(arr4)  # індекс загальний, наче масив лінійний
min_index

np.int64(81)

In [54]:
xy = np.unravel_index(min_index, arr4.shape)  # індекс перерахований на форму масиву (подвійний)
print("мінімум знаходиться за індексами:", ",".join( map(str, xy) ))

мінімум знаходиться за індексами:  8,1


In [55]:
print(
    "максимум знаходиться за індексами:", 
    ",".join( map(str, np.unravel_index(np.argmax(arr4), arr4.shape)) )
)

максимум знаходиться за індексами: 6,7


## Завдання 5
Створіть одновимірний масив із 15 випадкових цілих чисел від -10 до 10.
- Виведіть масив.
- За допомогою булевої індексації виберіть тільки додатні елементи.
- За допомогою булевої індексації виберіть тільки парні елементи.
- Виведіть обидва результати на екран.

In [62]:
arr5 = np.random.randint(-10,10,size=15)
print(arr5)
arr5

[  5  -3 -10   5  -6   0  -8   5   3   4   4   5   2   3   9]


array([  5,  -3, -10,   5,  -6,   0,  -8,   5,   3,   4,   4,   5,   2,
         3,   9], dtype=int32)

In [64]:
cond_index = arr5 > 0  # умова формує масив результатів для кожного з елементів
print(cond_index)
print(arr5[cond_index])  # умовна індексація

[ True False False  True False False False  True  True  True  True  True
  True  True  True]
[5 5 5 3 4 4 5 2 3 9]


In [65]:
print(arr5[arr5 % 2 == 0])  # умовна індексація одразу з умовою

[-10  -6   0  -8   4   4   2]


In [66]:
np.count_nonzero(arr5 % 2 == 0)  # підрахунок кількості елементів, що відповідають умові

np.int64(7)